server:
  port: 8081
  servlet:
    context-path: /planevent

spring:
  application:
    name: planevent-service

  data:
    mongodb:
      database: upp-db
      host: localhost
      port: 27017

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.niks: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
