server:
  port: 8083
  servlet:
    context-path: /plan-xapi

spring:
  application:
    name: plan-xapi

  main:
    web-application-type: reactive

  cloud:
    discovery:
      enabled: false

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.niks: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

services:
  planevent:
    base-url: http://localhost:8081/planevent
  promotion:
    base-url: http://localhost:8082/promotion
