server:
  port: 8082

spring:
  application:
    name: promotion-service

  main:
    web-application-type: reactive

  data:
    mongodb:
      host: localhost
      port: 27017
      database: upp-db
